#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=0
while [ $counter -lt 10 ];
do
    if [ $counter -eq 8 ]
    then
	echo -e "Best School\nHi"
    else
	echo "Best School"
    fi
    let counter=counter+1
done
